name: 02 - Workflow Events
on: 
    push:
    pull_request:
    # schedule:
    #     - cron: "*/15 * * * *" # Every 15 minutes
    workflow_dispatch:
jobs: 
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show The Trigger
              run: echo "I've been triggered by a(n) ${{ github.event_name }} event."

